[package]
name = "sss-bip39"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
fastcrypto = "0.1.5"
gf256 = { git = "https://github.com/asonnino/gf256.git", rev = "e54f759" }