# This section is considered when running `cargo deny check advisories`
# More documentation for the advisories section can be found here:
# https://embarkstudios.github.io/cargo-deny/checks/advisories/cfg.html
[advisories]
version = 2
ignore = ["RUSTSEC-2023-0071"]

# This section is considered when running `cargo deny check licenses`
# More documentation for the licenses section can be found here:
# https://embarkstudios.github.io/cargo-deny/checks/licenses/cfg.html
[licenses]
version = 2
# List of explicitly allowed licenses
# See https://spdx.org/licenses/ for list of possible licenses
# [possible values: any SPDX 3.11 short identifier (+ optional exception)].
allow = [
  "Apache-2.0",
  "MIT",
  "CC0-1.0",
  "BSD-3-Clause",
  "Unicode-DFS-2016",
  "MPL-2.0",
  "BSD-2-Clause",
]
# The confidence threshold for detecting a license from license text.
# The higher the value, the more closely the license text must be to the
# canonical license text of a valid SPDX license file.
# [possible values: any between 0.0 and 1.0].
confidence-threshold = 0.8

[[licenses.clarify]]
name = "ring"
expression = "LicenseRef-ring"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[licenses.private]
# If true, ignores workspace crates that aren't published, or are only
# published to private registries.
# To see how to mark a crate as unpublished (to the official registry),
# visit https://doc.rust-lang.org/cargo/reference/manifest.html#the-publish-field.
ignore = true

# This section is considered when running `cargo deny check bans`.
# More documentation about the 'bans' section can be found here:
# https://embarkstudios.github.io/cargo-deny/checks/bans/cfg.html
[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "deny"
skip = [
  "block-buffer:0.9.0", #  gf256 v0.3.0
  "convert_case:0.4.0", #  gf256 v0.3.0
  "der:0.6.1",          #  gf256 v0.3.0
  "digest:0.9.0",       #  gf256 v0.3.0
  "itertools:0.10.5",   #  gf256 v0.3.0
  "pem-rfc7468:0.6.0",  #  gf256 v0.3.0
  "pkcs8:0.9.0",        #  gf256 v0.3.0
  "sha2:0.9.9",         #  gf256 v0.3.0
  "spki:0.6.0",         #  gf256 v0.3.0
  "hermit-abi:0.3.9",   # fastcrypto v0.1.8
]
skip-tree = [
  # Some crates manipulating prints to stdout depend on an older version of windows-sys
  { name = "windows-sys", depth = 3, version = "0.48" },
  # The crate gf256 v0.3.0 depend on an older version of darling
  { name = "darling", depth = 3, version = "0.12.4" },
]

# This section is considered when running `cargo deny check sources`.
# More documentation about the 'sources' section can be found here:
# https://embarkstudios.github.io/cargo-deny/checks/sources/cfg.html
[sources]
# Lint level for what to happen when a crate from a crate registry that is not
# in the allow list is encountered
unknown-registry = "deny"
# Lint level for what to happen when a crate from a git repository that is not
# in the allow list is encountered
unknown-git = "deny"
allow-git = []

[sources.allow-org]
# 1 or more github.com organizations to allow git sources for
github = []
