[default]
workspace = true
skip-clean = true
run-types = ["Bins", "Doctests", "Examples", "Lib", "Tests"]
out = ["Html", "Xml"]
# Don't include test and benchmark code in the coverage result.
exclude-files = [
  "crates/**/benches/**/*",
  "crates/**/tests/**/*",
  "crates/**/test_utils/**/*",
]
args = ["--include-ignored"]
